default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: btd-blog_development

test:
  <<: *default
  database: btd-blog_test

staging:
  <<: *default
  database: btd-blog_staging
  username: root
  password: <%= Rails.application.credentials[:database][:password] %>

production:
  <<: *default
  database: btd-blog_production
  username: root
  password: <%= Rails.application.credentials[:database][:password] %>
