default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

development:
  <<: *default
  database: btd_blog_development

test:
  <<: *default
  database: btd_blog_test

staging:
  <<: *default
  database: btd_blog_staging
  username: root
  password: <%= Rails.application.credentials[:database][:password] %>

production:
  <<: *default
  database: btd_blog_production
  username: root
  password: <%= Rails.application.credentials[:database][:password] %>
